spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        '[format_sql]': true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sb951585!
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    group: true    
    locations: classpath:db/migration
logging:
  level:
    '[ir.saeidbabaei.bookstore.service]' : DEBUG
    '[ir.saeidbabaei.bookstore.controller]' : DEBUG
    '[ir.saeidbabaei.bookstore.exception]' : DEBUG 